### PR TITLE
Fixes black window on SSH login

### LINKED ISSUE #27: openframe won't start. Terminal being blacked out.
I'm on a fresh install of Raspbian Jessie on a RPi3. Once I install open frame I get these three errors on startup:

manpath: can't set the locale; make sure $LC_* and $LANG are correct
openfsetterm: terminal xterm-256color does not support --blank
setterm: cannot (un)set powersave mode: Inappropriate ioctl for device

and then the terminal is blacked out.  nothing (that I can see) happens when I type the 'openframe' command
screenshot 2016-12-13 09 13 32

[Someone else is having the same problem it looks like](http://raspberrypi.stackexchange.com/questions/48094/setterm-terminal-xterm-256color-does-not-support-blank)

### LINKED ISSUE #42: Disable autobooting Openframe on SSH login
As described in https://groups.google.com/d/msg/openframeio/X1BapUmEchs/QPE9UUzjAgAJ, enabling autostart causes issues with logins via SSH. The autostart routine should only run when booting the machine not logging in via SSH.

### PR DESCRIPTION
**Pull request by jvolker**
Fixes #42 
Fixes #27

### CODE REVIEW

File: scripts/autoboot.sh [hunk 1]
```diff
@@ -6,10 +6,16 @@ read -t 1 -n 1 key
...
-    # set the terminal text color to black
-    setterm --foreground black --background black --cursor off --clear all
-    # start up openframe as a background process
-    nohup openframe >/dev/null 2>&1 &
-fi
\ No newline at end of file
+    if [ -n "$SSH_CLIENT" ] || [ -n "$SSH_TTY" ]; then
+        echo "logged in via SSH"
+    else 
+        echo "logged in not via SSH"
```
Comment (jmwohl) [inline scripts/autoboot.sh]: If we're autobooting, we should keep output silent.

**Comment by jvolker** [comment]
@jmwohl thanks for checking this. My last commit should solve it.
